### ISSUE TITLE
Opt-in Phi Node elimination phase

### ISSUE THREAD

**Issue by artemdinaburg** [lifting-bits/rellic#102]
Currently rellic will (correctly! -- since they cannot be represented in C) bail on encountering LLVM Phi nodes. 

We do not transform the code automatically because we do not want to make changes to the bitcode the user gave us. An error message is produced letting them know to run reg2mem, which will remove Phi nodes.

This is a reasonable solution for interactive use, but for massive testing, we should include a way for rellic to opt-in to phi node elimination.

Suggestion to have something like `--remove-phi-nodes` that will run a simplified Phi node eliminator prior to converting to C.  (reg2mem does a few other things as well; we are only after Phi removal).

**Comment by pgoodman** [comment]
Something like this for eliminating just PHI nodes should work:
```c++
  std::vector<llvm::PHINode *> phi_nodes;
  for (auto &func : module) {
    if (func.isDeclaration()) {
      continue;
    }
    phi_nodes.clear();
    for (auto &block : func) {
      for (auto &inst : block) {
        if (auto phi = llvm::dyn_cast<llvm::PHINode>(&inst)) {
          phi_nodes.push_back(phi);
        }
      }
    }
    llvm::IRBuilder<> ir(&(func.getEntryBlock()));
    for (auto phi : phi_nodes) {
      ir.SetInsertPoint(&*func.getEntryBlock().getFirstInsertionPt());
      const auto alloca = ir.CreateAlloca(phi->getType());
      for (auto &use : phi->operands()) {
        const auto val = use.get();
        const auto block = phi->getIncomingBlock(use);
        ir.SetInsertPoint(block->getTerminator());
        ir.CreateStore(val, alloca);
      }
      ir.SetInsertPoint(phi->getParent()->getFirstNonPHIOrDbgOrLifetime());
      phi->replaceAllUsesWith(ir.CreateLoad(alloca));
      phi->eraseFromParent();
    }
  }
```

**Comment by surovic** [comment]
Thoughts on [llvm::DemotePHIToStack](https://github.com/llvm/llvm-project/blob/ddc4b56eef9fec990915470069a29e70bbde3711/llvm/include/llvm/Transforms/Utils/Local.h#L206) ?

**Comment by pgoodman** [comment]
Oh nice find! Looks like it works just about the same as my code. For referenceon on the implementation: [here](https://code.woboq.org/llvm/llvm/lib/Transforms/Utils/DemoteRegToStack.cpp.html#_ZN4llvm16DemotePHIToStackEPNS_7PHINodeEPNS_11InstructionE).
