### ISSUE TITLE
Migrating to the new LLVM pass manager

### ISSUE THREAD

**Issue by surovic** [lifting-bits/rellic#115]
We're widely using llvm::legacy pass managers. Might be a good idea to migrate to the new pass infrastructure eventually.

[How to write a new LLVM pass](https://llvm.org/docs/WritingAnLLVMNewPMPass.html)
[Using the new pass manager](https://llvm.org/docs/NewPassManager.html)

**Comment by frabert** [comment]
I think we should take this forced migration as an opportunity to ditch the LLVM passes altogether (apart from the few specific cases where it actually makes sense).

After all, most passes aren't actually operating on IR at all, and we are only using the pass managers as glorified `foreach` loops.

**Comment by surovic** [comment]
Fair point. I think that, however that keeping the "notion" and "design" of a pass is still very useful. I.e. having all current passes have a single, clearly defined entry point, strive for the passes to be independent and composable, etc. I know that we currently fall short of a lot of the things LLVM passes are usually known for, but I think it's still good to strive for that ideal.

**Comment by frabert** [comment]
Of course! What I mean is that we should roll our own class / concept of pass, instead of using LLVM passes.

**Comment by surovic** [comment]
@frabert I think this is solved already, right?

**Comment by frabert** [comment]
Yes, both the new LLVM pass manager has been used in place of the old one, and a new system for rellic passes.
