### ISSUE TITLE
Rellic API

### ISSUE THREAD

**Issue by pgoodman** [lifting-bits/rellic#209]
A straightforward decompilation API is needed, so that users of Rellic don't need to pull in all of Rellic's headers and copy & paste the rellic-decomp code just to get an AST. The API should take in an options structure of some kind and return a result type that is either a "decompilation" object, or an error object. A decompilation object would contain the unique_ptr of the ast unit, along with the provenance maps. The API should take as input a unique_ptr to an llvm module, and the module should be returned in the decompilation map. This is to communicate that the invoker of the API gives ownership of the module to rellic, "blessing" to to make any rellic-specific transforms, and rellic gives it back, so that the lifetime of the provenance maps, the module, and the ast unit are all the same.

The headers should continue to be provided as-is for more "advanced" users of rellic.

**Comment by frabert** [comment]
Would exceptions work as error signaling? Something like

```c++
class RellicException : public std::runtime_error { ... };

struct DecompilationResult {
   std::unique_ptr<clang::ASTUnit> ast;
   StmtToIRMap map;
};

DecompilationResult Decompile(llvm::Module& module); // Throws if an error has occurred
```

**Comment by pgoodman** [comment]
I was thinking that internally, Rellic could throw an exception, which would be caught inside of `Decompile`, and then converted to some kind of meangingful error return value. So then we might have:

```c++
struct Decompilation {
  std::unique_ptr<clang::ASTUnit> ast;
  ...
};
struct DecompilationError {
  std::unique_ptr<clang::ASTUnit> ast;
  std::string message;

  // If it makes sense, then a stack of actively processed values? I don't really know.
  std::vector<llvm::Value *> values_processed;
};
```

**Comment by frabert** [comment]
Closing as fixed
