### ISSUE TITLE
Provenance tracking for declarations

### ISSUE THREAD

**Issue by pgoodman** [lifting-bits/rellic#211]
Provenance tracking currently seems focused on `Stmt`s right now. This means that we lose out on information related to things like forward declarations, and function declarations, parameter declarations, etc. We should also want to associated `VarDecl`s with `alloca`s, for example. Another important use case is being able to look at a `DeclRefExpr` and say: this expression (`Stmt`) is related to X, and it's referenced decl is related to Y. We can't yet do the "related to Y" right now, and that's a very important use case in interactive workflows.

**Comment by frabert** [comment]
Can you provide an example in which the provenance as provided by `IRToASTVisitor::GetIRToValDeclMap` is not valid?

**Comment by pgoodman** [comment]
I don't want values -> decls, I want clang decls -> llvm decls ;-)

**Comment by frabert** [comment]
If that is the only issue, inverting the map should be easy :)

**Comment by pgoodman** [comment]
Also, if you can make it work for `VarDecl`s that are parameters and local vars then that'd be great too! That might need another map?

**Comment by frabert** [comment]
https://github.com/lifting-bits/rellic/blob/master/lib/AST/IRToASTVisitor.cpp#L364-L383

This is the section that deals with `clang::Decl`s, it should already store info about locals and paramenters

**Comment by pgoodman** [comment]
What is need is for all the provenance maps to be returned through the API, and if you pre-initialize bi-directional maps then that'd be even nicer :-)
