### ISSUE TITLE
Rendering of numeric 0 is inconsistent.

### ISSUE THREAD

**Issue by nickolas-pohilets** [lifting-bits/rellic#3]
Running rellic-decomp against attached bitcode file produces inconsistent results. I've attached the expected result, and one of the random results. Other results get produces as well.

[ret_0.zip](https://github.com/trailofbits/rellic/files/2779854/ret_0.zip)

**Comment by surovic** [comment]
Thanks for the report! Is `ret_0-actual.c` the input of a `C->IR->C` roundtrip or is `ret_0-in.ll` the input? If it's the latter, do you think I can use `ret_0-expected.c` as the roundtrip input?

**Comment by nickolas-pohilets** [comment]
* `ret_0-in.ll` - input
* `ret_0-actual.c` - actual output
* `ret_0-expected.c` - expected output

I think you can use `ret_0-expected.c` as a roundtrip input.

**Comment by surovic** [comment]
resolved by #40
