### ISSUE TITLE
Rellic crash during translation

### ISSUE THREAD

**Issue by pgarba** [lifting-bits/rellic#35]
Assertion failed: V.getBitWidth() == C.getIntWidth(type) && "Integer type is not the correct size for constant.", file C:\saturn\build_llvm\llvm-8.0.1.src\tools\clang\lib\AST\Expr.cpp, line 787
*** Aborted at 1566331860 (unix time) try "date -d @1566331860" if you are using GNU date ***
    @     0x7ffe06c3c31d raise
    @     0x7ffe06c3d321 abort
    @     0x7ffe06c3ed5e _get_wpgmptr
    @     0x7ffe06c3ec55 _get_wpgmptr
    @     0x7ffe06c3efe1 _wassert
    @     0x7ff74bce9f07 public: __cdecl clang::IntegerLiteral::IntegerLiteral(class clang::ASTContext const & __ptr64,class llvm::APInt const & __ptr64,class clang::QualType,class clang::SourceLocation) __ptr64
    @     0x7ff74bce9fd2 public: static class clang::IntegerLiteral * __ptr64 __cdecl clang::IntegerLiteral::Create(class clang::ASTContext const & __ptr64,class llvm::APInt const & __ptr64,class clang::QualType,class clang::SourceLocation)
    @     0x7ff74bc36b2c rellic::IRToASTVisitor::CreateLiteralExpr
    @     0x7ff74bc374cc rellic::IRToASTVisitor::GetOrCreateStmt
    @     0x7ff74bc372f9 rellic::IRToASTVisitor::GetOperandExpr
    @     0x7ff74bc397e1 rellic::IRToASTVisitor::visitBinaryOperator
    @     0x7ff74bc374ec rellic::IRToASTVisitor::GetOrCreateStmt
    @     0x7ff74bc2b7a4 rellic::GenerateAST::CreateBasicBlockStmts
    @     0x7ff74bc2ba0e rellic::GenerateAST::CreateRegionStmts
    @     0x7ff74bc2c6b6 rellic::GenerateAST::StructureAcyclicRegion
    @     0x7ff74bc2d7d9 rellic::GenerateAST::StructureRegion
    @     0x7ff74bc35072 std::_Func_impl_no_alloc<`lambda at C:\rellic\rellic\AST\GenerateAST.cpp:372:24',void,llvm::Region *>::_Do_call
    @     0x7ff74bc2ddc5 rellic::GenerateAST::runOnModule
    @     0x7ff74be62d51 public: bool __cdecl llvm::legacy::PassManagerImpl::run(class llvm::Module & __ptr64) __ptr64
    @     0x7ff74bcd67b8 main
    @     0x7ff74d566884 __scrt_common_main_seh
    @     0x7ffe078e7bd4 BaseThreadInitThunk
    @     0x7ffe090ece71 RtlUserThreadStart
[lifted.txt](https://github.com/trailofbits/rellic/files/3522445/lifted.txt)

**Comment by surovic** [comment]
Attached input no longer produces a crash. Probably resolved by #40
