### ISSUE TITLE
Z3ConvVisitor.cpp:157 Check failed: iter != c_decl_map.end()

### ISSUE THREAD

**Issue by artemdinaburg** [lifting-bits/rellic#50]
Tried a simple function that gives me an odd error on Z3ConvVisitor; invocation and bitcode below:

```
$ ./rellic-decomp-8.0 --input /store/artem/git/test/x86.bc --output /dev/stdout

F1121 12:21:17.359514 25086 Z3ConvVisitor.cpp:157] Check failed: iter != c_decl_map.end()
*** Check failure stack trace: ***
    @           0xcc82dd  google::LogMessage::Fail()
    @           0xcca76a  google::LogMessage::SendToLog()
    @           0xcc7ced  google::LogMessage::Flush()
    @           0xccb6f9  google::LogMessageFatal::~LogMessageFatal()
    @           0x800fb1  rellic::Z3ConvVisitor::GetCValDecl()

```

[x86.bc.gz](https://github.com/lifting-bits/rellic/files/3875919/x86.bc.gz)

**Comment by surovic** [comment]
Note: Likely related to the handling of basic blocks with `unreachanble` as their terminator. The BB doesn't have a path to the exit node of it's single-entry single-exit region. This messes up reaching conditions and subsequently messes up AST transformations, such as `NestedScopeCombiner` which finally produces nonsensical C output.

Fix should be pretty easy though by lowering unreachable to an `abort()` call or something similar and adding unconditional branches to the region exit node.

**Comment by surovic** [comment]
Seems like I was wrong with the above. `ret` instructions are essentially the same as `unreachable` in the context of single-entry single-exit regions and reaching conditions. And those seem to work. So back to the drawing board.
