### ISSUE TITLE
Handling LLVM PHI instructions

### ISSUE THREAD

**Issue by surovic** [lifting-bits/rellic#53]
So far we've been dealing with `phi` instructions by requiring preprocessing via `reg2mem`. This can lead to a large number of `alloca` instructions and consequently into a lot of local variables in the output C of rellic. So the question is wether there is a better way to do it.

**Comment by pgoodman** [comment]
https://15721.courses.cs.cmu.edu/spring2019/papers/19-compilation/kohn-icde2018.pdf

![Uploading image.png…]()

**Comment by pgoodman** [comment]
In some previous projects, I've

**Comment by surovic** [comment]
Yeah, this is exactly what `reg2mem` does afaik. I talked to @artemdinaburg about this and I think we agreed that we'd defer to the user to run `reg2mem` themselves. And if we encounter a `PHINode` we let the user know they should do that.

That being said, can I close this issue?
