### ISSUE TITLE
Install target for Makefile

### ISSUE THREAD

**Issue by ekilmer** [lifting-bits/rellic#54]
Having an `install` target for rellic will help when packaging rellic to include the necessary binaries and library artifacts, so that they can be distributed in a more lightweight package.

With PR #48 , users have the ability to use Docker to build, test, and run rellic. However, the Dockerfile in that PR produces an image that is fairly large, at around 2GB, with the `libraries` directory (inside the build directory) accounting for 1.4GB of that total.

It would be nice to use the `install` target to produce smaller Docker images that only include the necessary build artifacts required to develop with/run rellic.

**Comment by artemdinaburg** [comment]
I think this is now fixed :)
