### ISSUE TITLE
LLVM 9.0 support

### ISSUE THREAD

**Issue by evanrichter** [lifting-bits/rellic#55]
Hi, I'm trying to decompile some rust generated bitcode to see the output's equivalent c structure. I think if rellic supported llvm 9.0, it would be possible.

I'm using [noodle](https://github.com/gamozolabs/noodle) to test this. It's a dependency free serialization/deserialization library that is quick to compile.

`cargo rustc --release -- --emit=llvm-bc` will produce bitcode in ./target/release/deps/

The error in rellic is:
```
docker run --rm -t -i -v $(pwd):/test -w /test -u $(id -u):$(id -g) rellic-decomp-80 --input /test/target/release/deps/noodle-2a10fa4336dab943.bc --output /dev/stdout
F1128 18:38:31.484282     7 Util.cpp:89] Unable to parse module file /test/target/release/deps/noodle-2a10fa4336dab943.bc: Unknown attribute kind (60) (Producer: 'LLVM9.0.0-rust-1.39.0-stable' Reader: 'LLVM 8.0.0')
*** Check failure stack trace: ***
    @          0x1c7651d  google::LogMessage::Fail()
    @          0x1c789aa  google::LogMessage::SendToLog()
    @          0x1c75f2d  google::LogMessage::Flush()
    @          0x1c79939  google::LogMessageFatal::~LogMessageFatal()
    @           0x843d13  rellic::LoadModuleFromFile()
Aborted (core dumped)
```
key takeaway here: `(Producer: 'LLVM9.0.0-rust-1.39.0-stable' Reader: 'LLVM 8.0.0')`

obviously I'm using rellic built for llvm 8.0, and didn't really expect it to work.

**Comment by artemdinaburg** [comment]
LLVM9 & 10 support is on our radar, but you may be able to get a bit further if you disassemble your bitcode to text-based format via `llvm-dis-8` and re-assemble back to binary bitcode using llvm9's `llvm-as-9`. The text format tends to be more stable than the binary representation.

**Comment by artemdinaburg** [comment]
Rellic should now work up to LLVM11
