### ISSUE TITLE
Emit C global declarations in topological order

### ISSUE THREAD

**Issue by surovic** [lifting-bits/rellic#58]

**Comment by pgoodman** [comment]
Another option might be to forward declare everything?

**Comment by pgoodman** [comment]
Or both, e.g. emit in topological order, but for cycles, support forward declarations.

**Comment by surovic** [comment]
> Or both, e.g. emit in topological order, but for cycles, support forward declarations.

Yeah, that's the plan. We currently forward declare everything so I thought it might be neat to sometime reduce the amount of forward declarations by emitting in order. This is not really a priority feature or bug. More or less just a reminder.

**Comment by surovic** [comment]
@frabert Since #249 was closed. Do you think we can close this one as well?

**Comment by frabert** [comment]
I think we can!
