### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by leibo-hust** [lifting-bits/rellic#67]
Hi, I tring to install the rellic on ubuntu 18.04, but I met the error when running the command: `./scripts/build.sh`:

**FAILED: rellic/CMakeFiles/rellic.dir/AST/Util.cpp.o** 
/home/lb/mvm/rellic/rellic-build/libraries/llvm/bin/clang++  -DGFLAGS_IS_A_DLL=0 -DGOOGLE_GLOG_DLL_DECL="" -DNDEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -isystem . -isystem ../ -isystem libraries/llvm/include -isystem libraries/z3/include -isystem libraries/glog/include -isystem libraries/gflags/include -O2 -g -DNDEBUG   -Wall -Wextra -Wno-unused-parameter -Wno-c++98-compat -Wno-unreachable-code-return -Wno-nested-anon-types -Wno-extended-offsetof -Wno-variadic-macros -Wno-return-type-c-linkage -Wno-c99-extensions -Wno-ignored-attributes -Wno-unused-local-typedef -Wno-unknown-pragmas -Wno-unknown-warning-option -fPIC -fno-omit-frame-pointer -fvisibility-inlines-hidden -fno-exceptions -fno-asynchronous-unwind-tables -Wgnu-alignof-expression -Wno-gnu-anonymous-struct -Wno-gnu-designator -Wno-gnu-zero-variadic-macro-arguments -Wno-gnu-statement-expression -gdwarf-2 -g3 -O3 -Werror -pedantic -std=c++14 -MD -MT rellic/CMakeFiles/rellic.dir/AST/Util.cpp.o -MF rellic/CMakeFiles/rellic.dir/AST/Util.cpp.o.d -o rellic/CMakeFiles/rellic.dir/AST/Util.cpp.o -c ../rellic/AST/Util.cpp
../rellic/AST/Util.cpp:206:20: error: no matching constructor for initialization of 'clang::MemberExpr'
  return new (ctx) clang::MemberExpr(base, is_arrow, clang::SourceLocation(),
                   ^                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
libraries/llvm/include/clang/AST/Expr.h:2848:3: note: candidate constructor not viable: requires 9 arguments, but 8 were provided
  MemberExpr(Expr *Base, bool IsArrow, SourceLocation OperatorLoc,
  ^
libraries/llvm/include/clang/AST/Expr.h:2852:3: note: candidate constructor not viable: requires single argument 'Empty', but 8 arguments were provided
  MemberExpr(EmptyShell Empty)
  ^
libraries/llvm/include/clang/AST/Expr.h:2807:7: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 8 were provided
class MemberExpr final
      ^
1 error generated.

thanks a lot!

**Comment by leibo-hust** [comment]
@surovic

**Comment by leibo-hust** [comment]
@surovic

**Comment by surovic** [comment]
Hello, sorry for the late response. Will look at it ASAP.
