### ISSUE TITLE
Aborted at 1611523302 (unix time)

### ISSUE THREAD

**Issue by rofl0r** [lifting-bits/rellic#90]
after running ./rellic-build/tools/rellic-decomp-9.0 --input foo.exe.bc --output foo.c

(note that the path to the decompiler is different than mentioned in README)

i get:

```
error: unknown target triple '', please use -triple or -arch
*** Aborted at 1611523302 (unix time) try "date -d @1611523302" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x0) received by PID 21849 (TID 0x7fd16427fec0) from PID 0; stack trace: ***
    @     0x7fd1646893c0 (/home/rofl0r/ub/root/usr/lib/x86_64-linux-gnu/libpthread-2.31.so+0x153bf)
    @          0x1bcc80c (/home/rofl0r/ub/root/root/rellic-build/tools/rellic-decomp-9.0+0x1bcc80b)
    @           0x825922 (/home/rofl0r/ub/root/root/rellic-build/tools/rellic-decomp-9.0+0x825921)
Segmentation fault
```

ftr, foo.exe.bc was created by retdec-4.0 from a 2.8 meg win32 binary (retdec subsequently spent 5 days running on a single core in retdec-llvmir2hll which i subsequently killed, as i figured rellic might be able to do the same, and it pretty much looked like retdec was hung in an infinite loop as memory usage was constant at 32GB RAM for the whole time)

**Comment by rofl0r** [comment]
btw in case this is due to some external command being run that is supposed to be available, i installed my ubuntu 20.04 rootfs from the 20 mb base tarballs according to this:
https://github.com/sabotage-linux/sabotage/wiki/Running-a-minimal-ubuntu-rootfs-as-regular-user

then i installed the apt packages that were mentioned in readme.

so maybe some apt package that's installed by default on the ubuntu desktop needs to be added to the dependency list.

**Comment by ekilmer** [comment]
Just for posterity:

More relevant comments in #91 starting here https://github.com/lifting-bits/rellic/pull/91#issuecomment-767230442

**Comment by surovic** [comment]
And one from me for posterity. The issue lies here:
```
error: unknown target triple '', please use -triple or -arch
```
instead of the issue title.

**Comment by rofl0r** [comment]
> The issue lies here:

so what's actually the right way to specify arch or triple ? i tried

```
rellic-build-1/tools/rellic-decomp-9.0 -arch=x86 --input supercard_cd_271/SuperCardsd.exe.bc --output test.c
ERROR: unknown command line flag 'arch'
root@super:/root# FLAGS_arch=x86 rellic-build-1/tools/rellic-decomp-9.0 -fromenv=arch --input supercard_cd_271/SuperCardsd.exe.bc --output test.c
ERROR: unknown command line flag 'arch' (via --fromenv or --tryfromenv)
root@super:/root# FLAGS_arch=x86 rellic-build-1/tools/rellic-decomp-9.0 -fromenv=-arch --input supercard_cd_271/SuperCardsd.exe.bc --output test.c
ERROR: flag "-arch" begins with '-'
```
i failed in the same way to get any actually useful --help output.

**Comment by pgoodman** [comment]
@rofl0r can you attach your bitcode file here?

**Comment by rofl0r** [comment]
@pgoodman  https://0x0.st/-RQ3.xz
i added the target line as described in this post https://github.com/lifting-bits/rellic/pull/91#issuecomment-767247946 to the .ll file, but i get the same error as the author of that post described.
underlying issues seems to be that rellic doesn't work with llvm bytecode produced by other tools such as retdec, but only with the elite mcsema, which can only be used by people that can afford a copy of IDA pro even though there are dozens of free and powerful disassemblers that could be used in its place.

**Comment by pgoodman** [comment]
@rofl0r I was able to change the triple of the bitcode module using the following command:

```bash
clang -c ~/Downloads/bitcode/SuperCardsd.exe.bc -o ~/Downloads/bitcode/SuperCardsd.exe.ll -emit-llvm -target i486-pc-win32-unknown -S
```

That produces a LLVM assembly file with a triple. I then tried it on that file as follows:

```bash
./tools/rellic-decomp-12.0 --input ~/Downloads/bitcode/SuperCardsd.exe.bc --output /dev/stderr --lower_switch --remove_phi_nodes
```

This produced the following issue:
```
F1115 10:20:40.134071 255831552 ASTBuilder.cpp:326] Check failed: lhs && rhs Should not be null in CreateBinaryOp.
*** Check failure stack trace: ***
    @        0x103e2035f  google::LogMessageFatal::~LogMessageFatal()
    @        0x103e1c919  google::LogMessageFatal::~LogMessageFatal()
zsh: abort      ./tools/rellic-decomp-12.0 --input ~/Downloads/bitcode/SuperCardsd.exe.bc
```

@rofl0r we'd appreciate your help in making Rellic work with retdec-produced bitcode. Can you help us diagnose this issue by introducing additional logging here to help us determine which of `lhs` or `rhs` is null, and what they relate to in the original bitcode?
